use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!

abstract_target 'TweetieAbstract' do
  pod 'Alamofire'
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RealmSwift'
  pod 'RxRealm' 
  pod 'Unbox' 
  pod 'Then' 
  pod 'Reachability' 
  pod 'RxRealmDataSources' 


  target 'Tweetie' do 
     platform :ios, '12.0' 
     pod 'RxDataSources'
  end 

  target 'MacTweetie' do 
    platform :osx, '10.14'
  end

  target 'TweetieTests' do
    platform :ios, '12.0' 
    pod 'RxTest' 
    pod 'RxBlocking'
  end

end
